In [6]:
#Date-11/10/22
#1-print the NumPy version in your system
import numpy as np
print(np.__version__)

1.20.3


In [8]:
#2-convert a list of numeric value into a one-dimensional NumPy array
import numpy as np
l=[12.23, 13.32, 100, 36.32]
print('original list',l)
a=np.array(l)
print('list converted to array')
print(a)

original list [12.23, 13.32, 100, 36.32]
list converted to array
[ 12.23  13.32 100.    36.32]


In [9]:
#3-create a 3x3 matrix with values ranging from 2 to 10
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
#4-create a null vector of size 10 and update sixth value to 11
import numpy as np

x=np.arange(1,11)
print(x)

x[6]=11
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6 11  8  9 10]


In [13]:
#5-create an array with values ranging from 12 to 38
import pandas as pd
x=np.arange(12,39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [15]:
#7-convert an array to a float type
import numpy as np
x=np.arange(1,5,dtype=float)
print(x)

[1. 2. 3. 4.]


In [19]:
#alternate
import numpy as np
a=[1,2,3,4]

print('original array',a)

x=np.asfarray(a)
print('converted to float type',x)

original array [1, 2, 3, 4]
converted to float type [1. 2. 3. 4.]


In [21]:
#6- reverse an array (first element becomes last)
import numpy as np
a=np.arange(1,10)

print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [22]:
#8-create a 2d array with 1 on the border and 0 inside
import numpy as np
x=np.ones((5,5))
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
#9-add a border (filled with 0's) around an existing array.
import pandas as pd
a=np.ones((5,5))
print(a)

print("1 on the border and 0 around the array")
a=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 around the array
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [7]:
#Date-11/11/22
#10-create a 8x8 matrix and fill it with a checkerboard pattern.
import numpy as np
x=np.ones((3,3))
print("Checkerboard pattern:")
x=np.zeros((8,8),dtype='int')
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
#11- convert a list and tuple into arrays.
import numpy as np
my_list=[1, 2, 3, 4, 5, 6, 7, 8]
print('list to array')
print(np.asarray(my_list))
my_tuple=([8,4,6],[1,2,3])
print('tuple to array')
print(np.asarray(my_tuple))

list to array
[1 2 3 4 5 6 7 8]
tuple to array
[[8 4 6]
 [1 2 3]]


In [11]:
#12- append values to the end of an array
import numpy as np
x=[10,20,30]
print('original array')
print(x)

x=np.append(x,[[40,50,60],[70,80,90]])
print("After append values to the end of the array:")
print(x)

original array
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [13]:
#13-create an empty and a full array
import numpy as np
#create empty array
x=np.empty((3,4))
print(x)

y=np.full((3,3),6)
print(y)

[[9.81157772e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [7.56587583e-307 2.92966904e-033 4.21989908e-090 3.85589012e-057]
 [3.57194398e-062 4.85259759e-033 3.99910963e+252 8.67490129e-067]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [15]:
#14-convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array. 
import numpy as np
fvalues=[0, 12, 45.21, 34, 99.91, 32]
f=np.array(fvalues)
print('values in farenheight degrees')
print(f)
print("Values in  Centigrade degrees:")
print(np.round((5*f/9 - 5*32/9),2))

values in farenheight degrees
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [16]:
#15- find the real and imaginary parts of an array of complex numbers.
import numpy as np
x=np.sqrt([1+0j])
y = np.sqrt([0+1j])

print("Original array:x ",x)
print("Original array:y ",y)

print('Real part of array')
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of array
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


In [17]:
#16- find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements
import numpy as np
x=np.array([1,2,3],dtype=np.float64)
print('size of the array', x.size)
print('length of one array elment in bytes',x.itemsize)
print('total bytes consumed by elements of array',x.nbytes)

size of the array 3
length of one array elment in bytes 8
total bytes consumed by elements of array 24


In [18]:
#17- test whether each element of a 1-D array is also present in a second array. 
import numpy as np
array1=np.array([0, 10, 20, 40, 60])
print('array1',array1)
array2=[0,40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1,array2))

array1 [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [19]:
#18-find common values between two arrays.
import numpy as np
array1=np.array([0, 10, 20, 40, 60])
print('array1:',array1)

array2 = [10, 30, 40]
print("Array2: ",array2)

print("Common values between two arrays:")
print(np.intersect1d(array1,array2))

array1: [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [20]:
#19-get the unique elements of an array.
import numpy as np
x=np.array([10, 10, 20, 20, 30, 30])

print("Original array:")
print(x)

print('Unique values in array')
print(np.unique(x))

Original array:
[10 10 20 20 30 30]
Unique values in array
[10 20 30]


In [22]:
#20-find the set difference of two arrays. The set difference will return the sorted,
#unique values in array1 that are not in array2
import numpy as np

x=np.array([0, 10, 20, 40, 60, 80])
y=np.array([10, 30, 40, 50, 70, 90])

print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(x,y))


Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [23]:
#21-find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, 
#unique values that are in only one (not both) of the input arrays.
import numpy as np
x=np.array([0, 10, 20, 40, 60, 80])
y=np.array([10, 30, 40, 50, 70])
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(x,y))

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [26]:
#22-find the union of two arrays. Union will return the unique, 
#sorted array of values that are in either of the two input arrays
import numpy as np

x=np.array([0, 10, 20, 40, 60, 80])
y=np.array([10, 30, 40, 50, 70])

print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(x,y))

Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


In [27]:
#23- test whether all elements in an array evaluate to True.
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


In [29]:
#24- test whether any array element along a given axis evaluates to True
import numpy as np
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))


False
True
True
True


In [1]:
#25-construct an array by repeating
import numpy as np
a=[1, 2, 3, 4]
print("Original array")
print(a)
print("Repeating 2 times")
x=np.tile(a,2)
print(x)

Original array
[1, 2, 3, 4]
Repeating 2 times
[1 2 3 4 1 2 3 4]


In [3]:
#26- repeat elements of an array
import numpy as np
x=np.repeat(3,4)
print(x)

x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))

[3 3 3 3]
[1 1 2 2 3 3 4 4]


In [4]:
#27-find the indices of the maximum and minimum values along the given axis of an array. 
import numpy as np
x=np.array([1, 2, 3, 4, 5, 6])
print(x)

print('maximum values',np.argmax(x))
print('minimum values',np.argmin(x))

[1 2 3 4 5 6]
maximum values 5
minimum values 0


In [6]:
#28-compare two given arrays
import numpy as np
a=np.array([1,2])
b=np.array([4,5])

print("Array a: ",a)
print("Array b: ",b)

print("a > b")
print(np.greater(a,b))

print("a >= b")
print(np.greater_equal(a,b))

print("a < b")
print(np.less(a,b))

print("a <= b")
print(np.less_equal(a,b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [12]:
#29-sort an along the first, last axis of an array
import numpy as np

x=np.array([[2,5],[8,4]])
print(x)

print(np.sort(x))

print(np.sort(x,axis=0))

[[2 5]
 [8 4]]
[[2 5]
 [4 8]]
[[2 4]
 [8 5]]


In [16]:
#30- sort pairs of first name and last name return their indices. (first by last name, then by first name)
import pandas as pd
first_names=('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names=('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

x=np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


In [18]:
#31-get the values and indices of the elements that are bigger than 10 in a given array
import numpy as np
x=np.array([[0, 10, 20], [20, 30, 40]])
print('original array')
print(x)

print('values bigger than 10=',x[x>10])
print('their indices are ',np.nonzero(x>10))

original array
[[ 0 10 20]
 [20 30 40]]
values bigger than 10= [20 20 30 40]
their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [19]:
#32-save a NumPy array to a text file
x=np.array([1,2,3,4])

np.savetxt('file.out', x, delimiter=',')

In [20]:
#33- find the memory size of a NumPy array
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


In [25]:
#34- create an array of ones and an array of zeros
import numpy as np

print('all zeros')
print(np.zeros((2,3),dtype='int'))

print('all ones')
print(np.ones((2,4),dtype='float'))

all zeros
[[0 0 0]
 [0 0 0]]
all ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [28]:
#35-change the dimension of an array
import numpy as np
x=np.array([1,2,3,4,3,2])
print(x)
print(x.reshape(2,3))

#alternative
x.shape=(3,2)
print(x)

[1 2 3 4 3 2]
[[1 2 3]
 [4 3 2]]
[[1 2]
 [3 4]
 [3 2]]


In [29]:
#36- create a contiguous flattened array
import numpy as np

x=np.array([[10, 20, 30], [20, 40, 50]])
print(x)

print('flattened array')
y=np.ravel(x)
print(y)

[[10 20 30]
 [20 40 50]]
flattened array
[10 20 30 20 40 50]


In [33]:
#37-create a 2-dimensional array of size 2 x 3 (composed of 4-byte integer elements),
#also print the shape, type and data type of the array.
import numpy as np

x = np.array([[2, 4, 6], [6, 8, 10]])

print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(2, 3)
int32


In [34]:
#38- create a new shape to an array without changing its data.
import numpy as np
x=np.array([1, 2, 3, 4, 5, 6])
y=np.reshape(x,(3,2))
print(x)
print(y)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [35]:
#39-change the data type of an array. 
import numpy as  np
x=np.array([[2, 4, 6], [6, 8, 10]],np.int32)
print(x)

print('changing datatype')
y=x.astype(float)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
changing datatype
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [39]:
#40-create a new array of 3*5, filled with 2
import numpy as np
x=np.ones([3,3])*2
print(x)

y=np.full([5,2],2)
print(y)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


In [48]:
#41-create an array of 10's with the same shape and type of a given array.
import numpy as np
x=np.arange(4,dtype=np.int64)
#y=np.empty_like(x,10)
y=np.full_like(x,10)
print(x)
print(y)

[0 1 2 3]
[10 10 10 10]


In [49]:
#42-create a 3-D array with ones on a diagonal and zeros elsewhere
import numpy as np
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#43- create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere
import numpy as np
x=np.diagflat([4,5,6,8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [54]:
#44-create a 1-D array going from 0 to 50 and an array from 10 to 50.
x=np.arange(50)
print("Array from 0 to 50:")
print(x)

x=np.arange(10,50)
print("Array from 10 to 50:")
print(x)

Array from 0 to 50:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array from 10 to 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [51]:
#45-Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive
import numpy as np
x=np.linspace(2.5,6.5,30)
print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [56]:
#46-create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive
import numpy as np
x=np.logspace(2,5,20,endpoint=False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [60]:
#47-create an array which looks like below array
import numpy as np
x = np.tri(4, 3, -1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [61]:
#48- create an array which looks like below array
import numpy as np
x = np.triu(np.arange(2, 14).reshape(4, 3), -1)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


In [62]:
#49- collapse a 3-D array into one dimension array
import numpy as np
x=np.eye(3)
print(x)

y=np.ravel(x)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 0. 0. 0. 1. 0. 0. 0. 1.]


In [10]:
#Date 11/12/22
#50- find the 4th element of a specified array
import numpy as np
x=np.array([[2, 4, 6], [9, 8, 10]],np.int32)
print(x)

print("Forth e1ement of the array:")
e4=x.flat[3]
print(e4)

y=x.ravel()
print(y[3])

[[ 2  4  6]
 [ 9  8 10]]
Forth e1ement of the array:
9
9


In [11]:
#51-interchange two axes of an array.
import numpy as np
x=np.array([[1,2,3]])
print(x)

y=np.swapaxes(x,0,1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [12]:
#52- move axes of an array to new positions. Other axes remain in their original order.
import numpy as np
x=np.zeros((2,3,4))
print(x)
print(np.moveaxis(x, 0, -1).shape)
print(np.moveaxis(x, -1, 0).shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 4, 2)
(4, 2, 3)


In [13]:
#53- move the specified axis backwards, until it lies in a given position.
import numpy as np

x=np.ones((2,3,4,5))
print(np.rollaxis(x,3,1).shape)

(2, 5, 3, 4)


In [18]:
#54- convert specified inputs to arrays with at least one dimension
import numpy as np
x=12
print(np.atleast_1d(x))

x=np.arange(6).reshape(3,2)
print(np.atleast_1d(x))

print(np.atleast_1d(1, [3, 4]))

[12]
[[0 1]
 [2 3]
 [4 5]]
[array([1]), array([3, 4])]


In [20]:
#55-view inputs as arrays with at least two dimensions, three dimensions
import numpy as np
x=10

print("View inputs as arrays with at least two dimensions:")
print(np.atleast_2d(x))

x = np.arange(4.0).reshape(2, 2)
print(np.atleast_1d(x))
print("View inputs as arrays with at least three dimensions:")
x =15
print(np.atleast_3d(x))
x = np.arange(3.0)
print(np.atleast_3d(x))

View inputs as arrays with at least two dimensions:
[[10]]
[[0. 1.]
 [2. 3.]]
View inputs as arrays with at least three dimensions:
[[[15]]]
[[[0.]
  [1.]
  [2.]]]


In [21]:
#56- insert a new axis within a 2-D array
import numpy as np
x=np.zeros((3,4))
y=np.expand_dims(x,axis=1).shape
print(y)

(3, 1, 4)


In [22]:
#57-remove single-dimensional entries from a specified shape
import numpy as np
x=np.zeros((3,4,1))
print(np.squeeze(x).shape)

(3, 4)


In [27]:
#58-concatenate two 2-dimensional arrays
import numpy as np
a=np.array([[0, 1, 3], [5, 7, 9]])
b=np.array([[0, 2, 4], [6, 8, 10]])
c=np.concatenate((a,b),1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [28]:
#59-convert 1-D arrays as columns into a 2-D array.
import numpy as np
a=np.array((1,2,3))
b=np.array((4,5,6))
c=np.column_stack((a,b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
#60-convert (in sequence depth wise (along third axis)) two 1-D arrays into a 2-D array
import numpy as np
a=np.array([[10],[20],[30]])
b=np.array([[40],[50],[60]])
c=np.dstack((a,b))
print(c)

[[[10 40]]

 [[20 50]]

 [[30 60]]]


In [34]:
#61-split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.
import numpy as np
x=np.arange(1,15)
print("Original array:",x)
print("After splitting:")
print(np.split(x,[2,6]))

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [38]:
#62-split of an array of shape 4x4 it into two arrays along the second axis. 
import numpy as np
x=np.arange(16).reshape(4,4)
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x,[2,6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [39]:
#63-get the number of nonzero elements in an array
import numpy as np
x=np.array([[0, 10, 20], [20, 30, 40]])

print("Original array:")
print(x)

print("Number of non zero elements in the above array:")
print(np.count_nonzero(x))

Original array:
[[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
5


In [42]:
#64-create a 5x5 matrix with row values ranging from 0 to 4
x=np.zeros((5,5))
print(x)

print("Row values ranging from 0 to 4.")
x+=np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [43]:
#65- test whether specified values are present in an array
import numpy as np
x=np.array([[1.12, 2.0, 3.45], [2.33, 5.12, 6.0]],float)
print("Original array:")
print(x)

print(2 in x)
print(2.33 in x)

Original array:
[[1.12 2.   3.45]
 [2.33 5.12 6.  ]]
True
True


In [50]:
#66-create a vector of size 10 with values ranging from 0 to 1, both excluded.
import numpy as np
x=np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [51]:
#67-make an array immutable (read-only).
import numpy as np
x=np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

In [53]:
#68- sum of all the multiples of 3 or 5 below 100
import numpy as np
x=np.arange(1,100)

# find  multiple of 3 or 5
n=x[(x%3==0)|(x%5==0)]
print(n[:100])
# print sum the numbers
print(n.sum())


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [55]:
#69- create an array with 10^2 elements.
import numpy as np
x=np.arange(1e2)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [56]:
#70-create display every element of a NumPy array
import numpy as np
x=np.arange(12).reshape(3,4)
for x in np.nditer(x):
    print(x,end=' ')
print()

0 1 2 3 4 5 6 7 8 9 10 11 


In [61]:
#71- create and display every element of a NumPy array in Fortran order. 
import numpy as np
x=np.arange(12).reshape(3,4)
print("Elements of the array in Fortan array:")
for x in np.nditer(x, order="F"):
    print(x,end=' ')
print("\n")

Elements of the array in Fortan array:
0 4 8 1 5 9 2 6 10 3 7 11 



In [63]:
#72-create a 5x5x5 cube of 1's
import numpy as np
x=np.zeros((5,5,5)).astype(int)+1
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [3]:
#73-create an array of (3, 4) shape, multiply every element value by 3 and display the new array
import numpy as np

x=np.arange(1,13).reshape(3,4)
print(x)

for a in np.nditer(x,op_flags=['readwrite']):
    a[...]=3*a

print()
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]


In [5]:
#74-combine a one and a two dimensional array together and display their elements.
import numpy as np
x=np.arange(4)
print('one dimensional array')
print(x)

y=np.arange(8).reshape(2,4)
print("Two dimensional array:")
print(y)

for a,b in np.nditer([x,y]):
    print('%d:%d' %(a,b),)

one dimensional array
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [6]:
#75-create an array of zeros and three column types (integer, float, character)
import numpy as np
x=np.zeros((3),dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"), (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)

[(1, 2., b'Albert Einstein') (2, 2., b'Edmond Halley')
 (3, 3., b'Gertrude B. Elion')]


In [14]:
#76- create a function cube which cubes all the elements of an array
import numpy as np
def cube(e):
    it=np.nditer([e,None])
    for a, b in it:
        b[...]=a*a*a
    return it.operands[1]
print(cube([1,2,3]))

[ 1  8 27]


In [23]:
#77-create an array of (3, 4) shape and convert the array elements in smaller chunks
import numpy as np
x=np.arange(12).reshape(3,4)
print(x)

print("Above array in small chuncks:")
for a in np.nditer(x,flags=['external_loop'],order='F'):
    print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Above array in small chuncks:
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [25]:
#78-create a record array from a (flat) list of arrays.
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])

result=np.core.records.fromarrays([a1,a2,a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


In [26]:
#79-generate a generic 2D Gaussian-like array
import numpy as np
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like array:")
print(g)

2D Gaussian-like array:
[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0

In [3]:
#80-convert a NumPy array into Python list structure
import numpy as np

x=np.arange(12).reshape(3,4)
print(x)

y=x.tolist()
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
