In [4]:
#date 11/15/22
#143- extract first element of the second row and fourth element of fourth row from a given (4x4) array.
import numpy as np
arr=np.arange(16).reshape(4,4)
print('original data')
print(arr)

print("\nExtracted data: First element of the second row and fourth element of fourth row  ")
print(arr[[1,3],[0,3]])

original data
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: First element of the second row and fourth element of fourth row  
[ 4 15]


In [5]:
#144-program to extract second and third elements of the second and third rows from a given (4x4) array
import numpy as np
arr=np.arange(16).reshape(4,4)
print('original data')
print(arr)

print("\nExtracted data: Second and third elements of the second and third rows")
print(arr[1:3,1:3])

original data
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second and third elements of the second and third rows
[[ 5  6]
 [ 9 10]]


In [6]:
#145- program to extract first, third and fifth elements of the third and fifth rows from a given (6x6) array.
import numpy as np
arr=np.arange(36).reshape(6,6)
print('original data')
print(arr)

print("\nExtracted data: First, third and fifth elements of the third and fifth rows")
print(arr[2::2,::2])

original data
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Extracted data: First, third and fifth elements of the third and fifth rows
[[12 14 16]
 [24 26 28]]


In [14]:
#146-program to add two arrays A and B of sizes (3,3) and (,3)
import numpy as np
a=np.ones((3,3))
b=np.arange(3)

print("Original array:")
print("Array-1")
print(a)
print("Array-2")
print(b)

print('a+b ')
new_arr=a+b
print(new_arr)

Original array:
Array-1
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array-2
[0 1 2]
a+b 
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [16]:
#147- create an array that represents the rank of each item of a given array
import numpy as numpy

array = numpy.array([24, 27, 30, 29, 18, 14])
print("Original array:")
print(array)

argsort_array = array.argsort()
ranks_array = numpy.empty_like(argsort_array)
ranks_array[argsort_array] = numpy.arange(len(array))

print("\nRank of each item of the said array:")
print(ranks_array)

Original array:
[24 27 30 29 18 14]

Rank of each item of the said array:
[2 3 5 4 1 0]


In [19]:
#148-copy data from a given array to another array.
import numpy as np
x=np.array([24, 27, 30, 29, 18, 14])
print('original array')
print(x)

y=np.empty_like(x)
y[:]=x

print("\nCopy of the said array:")
print(y)

original array
[24 27 30 29 18 14]

Copy of the said array:
[24 27 30 29 18 14]


In [21]:
#149- find elements within range from a given array of numbers
import numpy as np
a=np.array([1, 3, 7, 9, 10, 13, 14, 17, 29])

print("Original array:")
print(a)

result=np.where(np.logical_and(a>=7,a<=20))
print("\nElements within range: index position")
print(result)

Original array:
[ 1  3  7  9 10 13 14 17 29]

Elements within range: index position
(array([2, 3, 4, 5, 6, 7], dtype=int64),)


In [20]:
#150-swap columns in a given array.
import numpy as np
arr=np.arange(12).reshape(3,4)
print('original array')
print(arr)

arr[:,[0,1]]=arr[:,[1,0]]
print('after swapping arrays columns')
print(arr)

original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
after swapping arrays columns
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [26]:
#151-get the row numbers in given array where at least one item is larger than a specified value
import numpy as np
num=np.arange(36)

arr1=np.reshape(num,[4,9])
print('original array')
print(arr1)

result=np.where(np.any(arr1>10,axis=1))

print("\nRow numbers where at least one item is larger than 10:")
print(result)

original array
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]

Row numbers where at least one item is larger than 10:
(array([1, 2, 3], dtype=int64),)


In [28]:
#152- to calculate the sum of all columns of a 2D NumPy array
import numpy as np
num=np.arange(36)
arr1=np.reshape(num,[4,9])
print('original array')
print(arr1)

result=arr1.sum(axis=0)
print("\nSum of all columns:")
print(result)

original array
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]

Sum of all columns:
[54 58 62 66 70 74 78 82 86]


In [30]:
#153-extract upper triangular part of a NumPy matrix
import numpy as np
num=np.arange(18)
arr1=np.reshape(num,[6,3])
print('original array')
print(arr1)

result=arr1[np.triu_indices(3)]
print("\nExtract upper triangular part of the said array:")
print(result)

result  = arr1[np.triu_indices(2)]
print("\nExtract upper triangular part of the said array:")
print(result)

original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

Extract upper triangular part of the said array:
[0 1 2 4 5 8]

Extract upper triangular part of the said array:
[0 1 4]


In [31]:
#154- get a copy of a matrix with the elements below the k-th diagonal zeroed
import numpy as np
result=np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
print("\nCopy of a matrix with the elements below the k-th diagonal zeroed:")
print(result)


Copy of a matrix with the elements below the k-th diagonal zeroed:
[[ 1  2  3]
 [ 4  5  6]
 [ 0  8  9]
 [ 0  0 12]]


In [32]:
#155-check whether a Numpy array contains a specified row
import numpy as np
num=np.arange(20)
arr1=np.reshape(num,[4,5])
print('original array')
print(arr1)

print([0, 1, 2, 3, 4] in arr1.tolist())
print([0, 1, 2, 3, 5] in arr1.tolist())
print([15, 16, 17, 18, 19] in arr1.tolist())

original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


In [37]:
#156-calculate averages without NaNs along a given array
import numpy as np
arr1=np.array([[10, 20 ,30], [40, 50, np.nan], [np.nan, 6, np.nan], [np.nan, np.nan, np.nan]])
print('original arrray')
print(arr1)

temp=np.ma.masked_array(arr1,np.isnan(arr1))
result=np.mean(temp,axis=1)

print("Averages without NaNs along the said array:")
print(result.filled(np.nan))

original arrray
[[10. 20. 30.]
 [40. 50. nan]
 [nan  6. nan]
 [nan nan nan]]
Averages without NaNs along the said array:
[20. 45.  6. nan]


In [38]:
#157- create a new array which is the average of every consecutive triplet of elements of a given array
import numpy as np
arr1=np.array([1,2,3, 2,4,6, 1,2,12, 0,-12,6])
print("Original array:")
print(arr1)

result=np.mean(arr1.reshape(-1,3),axis=1)
print("Average of every consecutive triplet of elements of the said array:")
print(result)

Original array:
[  1   2   3   2   4   6   1   2  12   0 -12   6]
Average of every consecutive triplet of elements of the said array:
[ 2.  4.  5. -2.]


In [43]:
#158- program to calculate average values of two given NumPy arrays
import numpy as np
array1 = [[0, 1], [2, 3]]
array2 = [[4, 5], [0, 3]]
print("Original arrays:")
print(array1)
print(array2)

print("Average values of two said numpy arrays:")
result=(np.array(array1)+np.array(array2))/2
print(result)

Original arrays:
[[0, 1], [2, 3]]
[[4, 5], [0, 3]]
Average values of two said numpy arrays:
[[2. 3.]
 [1. 3.]]


In [44]:
#159- program to rearrange columns of a given NumPy 2D array using given index positions
import numpy as np
array1 = np.array([[11, 22, 33, 44, 55],
             [66,  77,  88,  99, 100]])

print("Original arrays:")
print(array1)

i=[1,3,0,4,2]
result=array1[:,i]

print("New array:")
print(result)

Original arrays:
[[ 11  22  33  44  55]
 [ 66  77  88  99 100]]
New array:
[[ 22  44  11  55  33]
 [ 77  99  66 100  88]]


In [47]:
#160- find the k smallest values of a given NumPy array
import numpy as np
arr1=np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])

print("Original arrays:")
print(arr1)
k=4

result=np.argpartition(arr1,k)

print("\nk smallest values:")
print(arr1[result[:k]])

Original arrays:
[ 1.   7.   8.   2.   0.1  3.  15.   2.5]

k smallest values:
[0.1 1.  2.  2.5]


In [55]:
#161- create a white image of size 512x256
from PIL import Image
import numpy as np
a=np.full((512, 256, 3),255, dtype=np.uint8)
image = Image.fromarray(a, "RGB")
image.save("white.png", "PNG")

In [57]:
#162-Write a NumPy program to select from the first axis (K) by the indices tidx to get an array of shape (J=4, I=8) back.
import numpy as np

a=np.random.randint(0,10,(3,4,8))
print("Original array and shape:")
print(a)
print(a.shape)
print("--------------------------------")

tidx=np.random.randint(0,3,4)
print("tidex: ",tidx)
print("Result:")
print(a[tidx, np.arange(len(tidx)),:])

Original array and shape:
[[[2 2 5 2 6 5 7 0]
  [2 1 9 4 5 2 5 3]
  [6 9 6 4 6 0 6 7]
  [3 7 0 7 0 4 8 0]]

 [[4 1 6 6 3 4 2 4]
  [7 2 0 0 4 8 9 0]
  [7 9 8 5 0 7 4 1]
  [2 8 0 8 0 5 7 9]]

 [[7 5 9 4 5 1 6 4]
  [1 9 5 3 5 0 3 5]
  [2 5 6 3 3 6 9 3]
  [9 1 1 1 1 8 7 3]]]
(3, 4, 8)
--------------------------------
tidex:  [0 2 0 0]
Result:
[[2 2 5 2 6 5 7 0]
 [1 9 5 3 5 0 3 5]
 [6 9 6 4 6 0 6 7]
 [3 7 0 7 0 4 8 0]]


In [58]:
#163-Write a NumPy program to count the number of instances of a value occurring in one array on the condition of another array.
import numpy as np
x = np.array([10,-10,10,-10,-10,10])
y = np.array([.85,.45,.9,.8,.12,.6])

print("Original arrays:")
print(x)
print(y)

result=np.sum(x==10)&(y>0.5)

print("\nNumber of instances of a value occurring in one array on the condition of another array:")
print(result)

Original arrays:
[ 10 -10  10 -10 -10  10]
[0.85 0.45 0.9  0.8  0.12 0.6 ]

Number of instances of a value occurring in one array on the condition of another array:
[1 0 1 1 0 1]


In [60]:
#164-program to save as text a matrix which has in each row 2 float and 1 string at the end.
import numpy as np
matrix = [[1, 0, 'aaa'], [0, 1, 'bbb'], [0, 1, 'ccc']]
np.savetxt('test', matrix, delimiter='  ', header='string', comments='', fmt='%s')

In [56]:
#165- merge three given NumPy arrays of same shape
import numpy as np
arr1=np.random.random(size=(25,25,1))
arr2 = np.random.random(size=(25, 25, 1))
arr3 = np.random.random(size=(25, 25, 1))
print("Original arrays:")
print(arr1)
print(arr2)
print(arr3)

result=np.concatenate((arr1,arr2,arr3),axis=1)
print("\nAfter concatenate:")
print(result) 

Original arrays:
[[[0.70206793]
  [0.71400884]
  [0.21815316]
  [0.75098764]
  [0.29108292]
  [0.18248622]
  [0.72509108]
  [0.65421248]
  [0.41782122]
  [0.10510949]
  [0.2371468 ]
  [0.54174668]
  [0.49556054]
  [0.22047098]
  [0.09275246]
  [0.51696734]
  [0.45327574]
  [0.49235622]
  [0.17525964]
  [0.84764257]
  [0.7344699 ]
  [0.46690449]
  [0.82358151]
  [0.94254668]
  [0.72809054]]

 [[0.02623053]
  [0.9600665 ]
  [0.07222654]
  [0.10904983]
  [0.43330844]
  [0.87001855]
  [0.19881724]
  [0.95528821]
  [0.67322174]
  [0.9944881 ]
  [0.89462907]
  [0.90308824]
  [0.45668999]
  [0.41959608]
  [0.04184729]
  [0.35459673]
  [0.62092338]
  [0.96889679]
  [0.2784689 ]
  [0.55661053]
  [0.77810356]
  [0.13233087]
  [0.72829017]
  [0.66657376]
  [0.61105792]]

 [[0.98423068]
  [0.41286359]
  [0.21006939]
  [0.66282926]
  [0.15540142]
  [0.01083533]
  [0.86201265]
  [0.12869936]
  [0.37898747]
  [0.61408932]
  [0.60335921]
  [0.93455243]
  [0.57615003]
  [0.17098925]
  [0.06733138]
  [0

In [7]:
#Date-11/16/22
#166- combine last element with first element of two given ndarray with different shapes
import numpy as np
arr1=np.array(['PHP', 'JS', 'C++'])
arr2=np.array(['Python', 'C#', 'NumPy'])

#result=np.r_[arr1[:-1], [arr1[-1]+arr2[0]], arr2[1:]]  
result=np.concatenate((arr1,arr2))
print(result)

['PHP' 'JS' 'C++' 'Python' 'C#' 'NumPy']


In [8]:
#167-program to convert a Python dictionary to a NumPy ndarray.
import numpy as np
from ast import literal_eval
udict = """{"column0":{"a":1,"b":0.0,"c":0.0,"d":2.0},
   "column1":{"a":3.0,"b":1,"c":0.0,"d":-1.0},
   "column2":{"a":4,"b":1,"c":5.0,"d":-1.0},
   "column3":{"a":3.0,"b":-1.0,"c":-1.0,"d":-1.0}
  }"""
t = literal_eval(udict)
print("\nOriginal dictionary:")
print(t)
print("Type: ",type(t))
result_nparra = np.array([[v[j] for j in ['a', 'b', 'c', 'd']] for k, v in t.items()])
print("\nndarray:")
print(result_nparra)
print("Type: ",type(result_nparra))


Original dictionary:
{'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0}, 'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0}, 'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0}, 'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
Type:  <class 'dict'>

ndarray:
[[ 1.  0.  0.  2.]
 [ 3.  1.  0. -1.]
 [ 4.  1.  5. -1.]
 [ 3. -1. -1. -1.]]
Type:  <class 'numpy.ndarray'>


In [2]:
#168- convert Pandas dataframe to NumPy array with headers
import numpy as np
import pandas as pd
np_arr=np.random.rand(12,3)

print("Original Numpy array:")
print(np_arr)

print('type: ',type(np_arr))

df=pd.DataFrame(np.random.rand(12,3),columns=['A','B','C'])
print("\nPanda's DataFrame: ")
print(df)
print("Type: ",type(df))

Original Numpy array:
[[0.99144546 0.84369372 0.31654519]
 [0.32744563 0.1706919  0.5944594 ]
 [0.25880548 0.86523481 0.87306224]
 [0.37429426 0.63179754 0.93861187]
 [0.38598004 0.86277257 0.55522373]
 [0.60026569 0.26833567 0.59340956]
 [0.60474989 0.83336097 0.90910735]
 [0.55985312 0.42085703 0.4816122 ]
 [0.04246018 0.84761416 0.52332424]
 [0.07911793 0.80342151 0.46616652]
 [0.46180092 0.74631625 0.89118342]
 [0.42819293 0.8535487  0.76214469]]
type:  <class 'numpy.ndarray'>

Panda's DataFrame: 
           A         B         C
0   0.505472  0.425844  0.708121
1   0.455857  0.289245  0.558709
2   0.368958  0.401297  0.432337
3   0.506002  0.223118  0.884642
4   0.514947  0.698115  0.087160
5   0.836952  0.110339  0.870656
6   0.690559  0.535757  0.539514
7   0.429264  0.661828  0.092353
8   0.534380  0.946017  0.400476
9   0.845187  0.635670  0.173800
10  0.708496  0.556177  0.408127
11  0.399994  0.898201  0.001496
Type:  <class 'pandas.core.frame.DataFrame'>


In [5]:
#169-program to get all 2D diagonals of a 3D NumPy array
import numpy as np
np_arr=np.arange(3*4*5).reshape(3,4,5)
print('original array')
print(np_arr)

print("Type: ",type(np_arr))

result=np.diagonal(np_arr,axis1=1,axis2=2)
print("\n2D diagonals: ")
print(result)

original array
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
Type:  <class 'numpy.ndarray'>

2D diagonals: 
[[ 0  6 12 18]
 [20 26 32 38]
 [40 46 52 58]]


In [9]:
#170-Create a 2-dimensional array of size 2 x 3, composed of 4-byte integer elements.
#Write a NumPy program to find the number of occurrences of a sequence in the said array
import numpy as np
np_array=np.array([[1, 2, 3], [2, 1, 2]], np.int32)
print('original array')
print(np_array)

print(np_array)
print("Type: ",type(np_array))
print("Sequence: 1,2",)
result = repr(np_array).count("1, 2")
print("Number of occurrences of the said sequence:",result)

original array
[[1 2 3]
 [2 1 2]]
[[1 2 3]
 [2 1 2]]
Type:  <class 'numpy.ndarray'>
Sequence: 1,2
Number of occurrences of the said sequence: 2


In [15]:
#171-search the index of a given array in another given array
import numpy as np
np_arr=np.array([[1,2,3], [4,5,6] , [7,8,9], [10, 11, 12]])
test_arr=np.array([4,5,6])

print("Index of the searched array in the original array:")
print(np.where((np_arr==test_arr).all(1))[0])

Index of the searched array in the original array:
[1]


In [16]:
#172- find and store non-zero unique rows in an array after comparing each row with other row in a given matrix
import numpy as np
arr=np.array([[ 1,  1,  0],
                 [ 0,  0,  0],
                 [ 0,  2,  3],
                 [ 0,  0,  0],
                 [ 0, -1,  1],
                 [ 0,  0,  0]])

temp={(0,0,0)}
result=[]

for idx, row in enumerate(map(tuple,arr)):
    if row not in temp:
        result.append(idx)
        
print("\nNon-zero unique rows:")
print(arr[result])


Non-zero unique rows:
[[ 1  1  0]
 [ 0  2  3]
 [ 0 -1  1]]


In [17]:
#173- set zero to lower triangles along the last two axes of a three-dimensional of a given array
import numpy as np
arr=np.ones((1,8,8))
print('original array')
print(arr)

result=np.triu(arr,k=1)
print(result)

original array
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]
[[[0. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [18]:
#174-get the number of items, array dimensions, number of array dimensions and the memory size of each element of a given array.

import numpy as np
arr_num=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print('original array')
print(arr_num)

print("\nNumber of items of the said array:")
print(arr_num.size)

print("\nArray dimensions:")
print(arr_num.shape)

print("\nNumber of array dimensions:")
print(arr_num.ndim)

print("\nMemory size of each element of the said array")
print(arr_num.itemsize)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Number of items of the said array:
12

Array dimensions:
(3, 4)

Number of array dimensions:
2

Memory size of each element of the said array
4


In [19]:
#175-create an 1-D array of 20 elements. Now create a new array of shape (5, 4) 
#from the said array, then restores the reshaped array into a 1-D array
import numpy as np
arr=np.arange(20).reshape(5,4)
print('original array')
print(arr)

print("\nRestore the reshaped array into a 1-D array:")
print(arr.flatten())

original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Restore the reshaped array into a 1-D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
#176-create an array of 4,5 shape and swap column1 with column4.
import numpy as np
arr=np.arange(20).reshape(4,5)
print('original array')
print(arr)

print("\nAfter swapping column1 with column4:")
arr[:,[0,3]]=arr[:,[3,0]]
print(arr)

original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

After swapping column1 with column4:
[[ 3  1  2  0  4]
 [ 8  6  7  5  9]
 [13 11 12 10 14]
 [18 16 17 15 19]]


In [25]:
#177-to create an array of 4,5 shape and to reverse the rows of the said array. 
#After reversing 1st row will be 4th and 4th will be 1st, 2nd row will be 3rd row and 3rd row will be 2nd row
import numpy as np
arr=np.arange(20).reshape(4,5)
print('original array')
print(arr)

print('after reversing')
arr[:]=arr[3::-1]
print(arr)

original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
after reversing
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [27]:
#178- replace all the nan (missing values) of a given array with the mean of another array.
import numpy as np
arr1=np.arange(20).reshape(4,5)
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan, 7, np.nan]])

print('original arrays')
print(arr1)
print(arr2)

print("\nAll the nan of array_nums2 replaced by the mean of array_nums1:")
arr2[np.isnan(arr2)]=np.nanmean(arr1)
print(arr2)

original arrays
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1.  2. nan]
 [ 4.  5.  6.]
 [nan  7. nan]]

All the nan of array_nums2 replaced by the mean of array_nums1:
[[1.  2.  9.5]
 [4.  5.  6. ]
 [9.5 7.  9.5]]


In [28]:
#179-fetch all items from a given array of 4,5 shape which are either greater than 6 and a multiple of 3
import numpy as np
arr1=np.arange(20).reshape(4,5)
print('original array')
print(arr1)

result=arr1[(arr1>6)& (arr1%3==0)]
print(result)

original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 9 12 15 18]


In [31]:
#180-check whether the dimensions of two given arrays are same or not.
import numpy as np
def test_arr_dims(ar1,ar2):
    try:
        ar1+ar2
    except ValueError:
        return 'Different Dimensions'
    else:
        return 'same dimensins'
    
ar1 = np.arange(20).reshape(4,5)
ar2 = np.arange(20).reshape(4,5)
print(test_arr_dims(ar1, ar2))

ar1 = np.arange(20).reshape(5,4)
ar2 = np.arange(20).reshape(4,5)
print(test_arr_dims(ar1, ar2))

same dimensins
Different Dimensions


In [33]:
#181- place a specified element in specified time randomly in a specified 2D array.
import numpy as np
n=4
i=3
e=10

arr1=np.zeros((n,n))
print('original array')
print(arr1)

np.put(arr1,np.random.choice(range(n*n),i,replace=False),e)
print("\nPlace a specified element in specified time randomly:")
print(arr1)

original array
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Place a specified element in specified time randomly:
[[ 0.  0.  0. 10.]
 [10.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0. 10.  0.  0.]]


In [1]:
#Date-11/18/22
#182-subtract the mean of each row of a given matrix.
import numpy as np
print('original matrix')
X=np.random.rand(5,10)
print(X)

print("\nSubtract the mean of each row of the said matrix:\n")
Y=X-X.mean(axis=1,keepdims=True)
print(Y)

original matrix
[[0.35810027 0.8002866  0.34846004 0.58750016 0.00721699 0.76716816
  0.18366533 0.68999792 0.82663329 0.41069464]
 [0.85907562 0.98336297 0.71094169 0.67266807 0.75970028 0.17703498
  0.59598943 0.10530365 0.28877394 0.82317421]
 [0.92729505 0.36669866 0.41267483 0.5973011  0.56487927 0.14927488
  0.47007075 0.9761135  0.93627583 0.66505037]
 [0.43583383 0.64536681 0.64050286 0.28637545 0.11313287 0.78049791
  0.27314326 0.71353767 0.86163285 0.8450535 ]
 [0.41823008 0.3800186  0.93156432 0.70918208 0.68652789 0.5680764
  0.50967857 0.40545261 0.13411421 0.21825288]]

Subtract the mean of each row of the said matrix:

[[-0.13987206  0.30231426 -0.1495123   0.08952782 -0.49075535  0.26919582
  -0.31430701  0.19202558  0.32866095 -0.0872777 ]
 [ 0.26147314  0.38576049  0.1133392   0.07506558  0.1620978  -0.42056751
  -0.00161305 -0.49229883 -0.30882855  0.22557173]
 [ 0.32073163 -0.23986477 -0.19388859 -0.00926233 -0.04168415 -0.45728854
  -0.13649267  0.36955007  0.3297

In [2]:
#183-test whether a given 2D array has null columns or not.
import numpy as np
print('Original Aray')
nums=np.random.randint(0,3,(4,10))
print(nums)
print("\nTest whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

Original Aray
[[2 2 0 1 1 0 0 2 2 0]
 [2 1 1 0 1 2 0 2 0 0]
 [1 0 2 2 2 2 2 2 1 0]
 [2 0 1 1 1 2 0 1 2 2]]

Test whether the said array has null columns or not:
False


In [5]:
#184-create an array using generator function that generates 15 integers
import numpy as np
x=np.arange(15, dtype=float)
print(x)

def generate():
    for n in range(15):
        yield n
nums=np.fromiter(generate(),dtype=float,count=-1)
print('new_arre')
print(nums)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
new_arre
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [6]:
#185-create a new vector with 2 consecutive 0 between two values of a given vector
import numpy as np
nums=np.array([1,2,3,4,5,6,7,8])
print('original array')
print(nums)
p=2
new_nums=np.zeros(len(nums)+(len(nums)-1)*(p))
new_nums[::p+1] = nums
print("\nNew array:")
print(new_nums)

original array
[1 2 3 4 5 6 7 8]

New array:
[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5. 0. 0. 6. 0. 0. 7. 0. 0. 8.]


In [11]:
#186-program to multiply an array of dimension (2,2,3) by an array with dimensions (2,2)
import numpy as np
nums1=np.ones((2,2,3))
nums2=3*np.ones((2,2))

print('original arrays')
print(nums1)

new_array=nums1*nums2[:,:,None]
print(new_array)

original arrays
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]]]


In [12]:
#187-convert a given vector of integers to a matrix of binary representation
import numpy as np
nums = np.array([0, 1, 3, 5, 7, 9, 11, 13, 15])
print("Original vector:")
print(nums)
bin_nums = ((nums.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print("\nBinary representation of the said vector:")
print(bin_nums[:,::-1])

Original vector:
[ 0  1  3  5  7  9 11 13 15]

Binary representation of the said vector:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 1 1]]


In [5]:
#188-extract rows with unequal values (e.g. [1,1,2]) from 10x3 matrix.
import numpy as np
nums=np.random.randint(0,4,(6,3))
print('original vector')
print(nums)

new_nums=np.logical_and.reduce(nums[:,1:]==nums[:,:-1],axis=1)
result=nums[~new_nums]
print('\nresult')
print(result)

original vector
[[3 3 2]
 [1 0 0]
 [3 3 2]
 [1 1 1]
 [2 1 2]
 [1 2 3]]

result
[[3 3 2]
 [1 0 0]
 [3 3 2]
 [2 1 2]
 [1 2 3]]


In [6]:
#189-find rows of a given array of shape (8,3) that contain elements of each row of another given array of shape (2,2).
import numpy as np
nums1=np.random.randint(0,6,(6,4))
nums2=np.random.randint(0,6,(2,3))

print('original array')
print(nums1)
print('\n',nums2)

temp=(nums1[...,np.newaxis,np.newaxis]==nums2)
rows = (temp.sum(axis=(1,2,3)) >= nums2.shape[1]).nonzero()[0]
print("\nRows of a given array that contain elements of each row of another given array:")
print(rows)

original array
[[3 1 5 0]
 [1 1 4 2]
 [0 4 5 0]
 [3 1 0 4]
 [4 2 4 1]
 [5 3 2 3]]

 [[0 0 2]
 [0 4 3]]

Rows of a given array that contain elements of each row of another given array:
[0 2 3 4 5]


In [7]:
#190-create a record array from a given regular array
import numpy as np
arr1=np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print('original array')
print(arr1)

print("\nRecord array;")
result=  (arr1.T,names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

original array
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]


In [14]:
#191-get the block-sum (block size is 5x5) from a given array of shape 25x25
import numpy as np
arr1=np.ones((25,25))
k=5

print('original array')
print(arr1)

result=np.add.reduceat(np.add.reduceat(arr1, np.arange(0, arr1.shape[0], k), axis=0),np.arange(0, arr1.shape[1], k), axis=1)
print("\nBlock-sum (5x5) of the said array:")
print(result)

original array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1.

In [9]:
#192- program to extract all the contiguous 4x4 blocks from a given random 12x12 matrix


In [10]:
#193-test whether numpy array is faster than Python list or not.

In [11]:
#194-create two arrays with shape (300,400, 5), fill values using unsigned integer (0 to 255). 
#Insert a new axis that will appear at the beginning in the expanded array shape. Now combine the said two arrays into one

In [ ]:
#195-program to remove the first dimension from a given array of shape (1,3,4).