In [6]:
#Date 11/24/22
#1-compute the multiplication of two given matrixes
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]

print('original matrix')
print(p)
print(q)

result=np.dot(p,q)
print(result)

original matrix
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [7]:
#2-compute the outer product of two given vectors
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]

result=np.outer(p,q)
print(result)

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [8]:
#3-compute the cross product of two given vectors
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]

r1=np.cross(p,q)
r2=np.cross(q,p)
print(r1)
print(r2)

[ 2 -3]
[-2  3]


In [11]:
#4-compute the determinant of a given square array
import numpy as np
from numpy import linalg as la
a=np.array([[1, 0], [1, 2]])
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [12]:
#5-evaluate Einstein's summation convention of two given multidimensional arrays
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
result =  np.einsum("n,n", a, b)
print("Einstein’s summation convention of the said arrays:")
print(result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result)

Original 1-d arrays:
[1 2 3]
[0 1 0]
Einstein’s summation convention of the said arrays:
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [3]:
#Date-11/27/22
#6-compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.
import numpy as np
a=np.array([1,2,5])
b=np.array([2,1,0])

result=np.inner(a,b)
print(result)

print("Inner product of the said vectors:")
x=np.arange(9).reshape(3,3)
y=np.arange(3,12).reshape(3,3)
print("Higher dimension arrays:")
print(x)
print(y)

result=np.inner(x,y)
print(result)

4
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [4]:
#7- compute the eigenvalues and right eigenvectors of a given square array.
import numpy as np
m=np.mat('3 -2;1 0')
print('original matrix')
print(m)
w,v=np.linalg.eig(m)
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

original matrix
[[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [6]:
#8-compute the Kronecker product of two given mulitdimension arrays
import numpy as np
a=np.array([1,2,3])
b=np.array([0,1,0])

print('original array')
print(a)
print(b)

result=np.kron(a,b)
print("Kronecker product of the said arrays:")
print(result)

x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.kron(x, y)
print("Kronecker product  of the said arrays:")
print(result)

original array
[1 2 3]
[0 1 0]
Kronecker product of the said arrays:
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Kronecker product  of the said arrays:
[[ 0  0  0  3  4  5  6  8 10]
 [ 0  0  0  6  7  8 12 14 16]
 [ 0  0  0  9 10 11 18 20 22]
 [ 9 12 15 12 16 20 15 20 25]
 [18 21 24 24 28 32 30 35 40]
 [27 30 33 36 40 44 45 50 55]
 [18 24 30 21 28 35 24 32 40]
 [36 42 48 42 49 56 48 56 64]
 [54 60 66 63 70 77 72 80 88]]


In [7]:
#9-compute the condition number of a given matrix
import numpy as np
from numpy import linalg as LA

a=np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)

print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


In [8]:
#10-find a matrix or vector norm
import numpy as np
v=np.arange(7)
result=np.linalg.norm(v)
print('vector norm')
print(result)

m=np.mat('1 -2; 3 4')
result=np.linalg.norm(m)
print('matrix norm')
print(result)

vector norm
9.539392014169456
5.477225575051661


In [13]:
#11- compute the determinant of an array
import numpy as np
a=np.array([[1,2],[3,4]])
print('original array')
print(a)

result=np.linalg.det(a)
print("Determinant of the said array:")
print(result)

original array
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


In [16]:
#12-compute the inverse of a given matrix
import numpy as np
m=np.array([[1,2],[3,4]])
print('original matrix')
print(m)

result=np.linalg.inv(m)
print(result)

original matrix
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
#13-calculate the QR decomposition of a given matrix
import numpy as np
m=np.array([[1,2],[3,4]])
print('original array')
print(m)

result=np.linalg.qr(m)
print(result)

original array
[[1 2]
 [3 4]]
(array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [18]:
#14- compute the condition number of a given matrix
import numpy as np
m=np.array([[1,2],[3,4]])
print('original array')
print(m)

result=np.linalg.cond(m)
print(result)

original array
[[1 2]
 [3 4]]
14.933034373659268


In [19]:
#15- compute the sum of the diagonal element of a given array.
import numpy as np
m=np.arange(6).reshape(2,3)
print('original matrix')
print(m)

result=np.trace(m)
print(result)

original matrix
[[0 1 2]
 [3 4 5]]
4


In [24]:
#16-get the lower-triangular L in the Cholesky decomposition of a given array.
import numpy as np
a=np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print('original array')
print(a)

l=np.linalg.cholesky(a)
print("Lower-trianglular L in the Cholesky decomposition of the said array:")
print(l)

original array
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
Lower-trianglular L in the Cholesky decomposition of the said array:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]


In [26]:
#17-get the qr factorization of a given array
import numpy as np
a=np.array([[4, 12, -14], [12, 37, -53], [-14, -53, 98]], dtype=np.int32)
print('original array')
print(a)

q,r=np.linalg.qr(a)
print(q)
print()
print(r)

original array
[[  4  12 -14]
 [ 12  37 -53]
 [-14 -53  98]]
[[-0.21199958 -0.27930103  0.93650794]
 [-0.63599873 -0.68815735 -0.34920635]
 [ 0.74199852 -0.66964945 -0.03174603]]

[[-18.86796226 -65.4018692  109.39178122]
 [  0.           6.67798664 -25.24309237]
 [  0.           0.           2.28571429]]


In [28]:
#18-compute the factor of a given array by Singular Value Decomposition.
import numpy as np
a=np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
print('original array')
print(a)

u,s,v=np.linalg.svd(a,full_matrices=False)
q,r=np.linalg.qr(a)
print("Factor of a given array  by Singular Value Decomposition:")
print("U=\n", u, "\ns=\n", s, "\nV=\n", v)

original array
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
Factor of a given array  by Singular Value Decomposition:
U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


In [ ]:
#19- calculate the Frobenius norm and the condition number of a given array
import numpy as np
a = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(a)
print("Frobenius norm and the condition number:")
print(np.linalg.norm(a, 'fro'))
print(np.linalg.cond(a, 'fro'))