In [5]:
#Date 11/28/22
#1-generate five random numbers from the normal distribution
import numpy as np
x=np.random.normal(size=5)
print(x)

[ 0.31635564  0.05211871 -0.24031064  0.11267157 -0.03253548]


In [6]:
#2-generate six random integers between 10 and 30
import numpy as np
x=np.random.randint(low=10, high=30, size=6)
print(x)

[24 25 10 28 23 11]


In [11]:
#3-create a 3x3x3 array with random values
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.85721513 0.89106772 0.81665679]
  [0.61205005 0.88068591 0.51927494]
  [0.81757489 0.53529889 0.29010669]]

 [[0.6161213  0.97155652 0.41005752]
  [0.29280189 0.57366408 0.50637117]
  [0.16648493 0.50831588 0.41802744]]

 [[0.72403439 0.31809568 0.31711324]
  [0.87825166 0.20143164 0.13672402]
  [0.37516881 0.94752781 0.03715388]]]


In [12]:
#4-create a 5x5 array with random values and find the minimum and maximum values
import numpy as np
x=np.random.random((5,5))
print(x)

xmin,xmax=x.min(),x.max()
print('minimum value in the array=',xmin)
print('maximum value in the array=',xmax)

[[0.97770213 0.57273047 0.36187625 0.06768504 0.49187148]
 [0.67722431 0.41446145 0.49248136 0.29478671 0.62862698]
 [0.08979461 0.2128812  0.37332968 0.59426163 0.47920424]
 [0.2739633  0.19984787 0.3262279  0.83854526 0.33138749]
 [0.88565548 0.76623336 0.75127727 0.38802372 0.54578022]]
minimum value in the array= 0.06768504204813552
maximum value in the array= 0.9777021330453229


In [14]:
#5-create a random 10x4 array and extract the first five rows of the array and store them into a variable
import numpy as np
x=np.random.rand(10,4)
print(x)

y=x[:5,:]
print('first five rows of the array')
print(y)

[[0.49634341 0.26244877 0.9943427  0.94701315]
 [0.14840418 0.8325256  0.38044768 0.47814738]
 [0.24444211 0.02846687 0.39094955 0.1748491 ]
 [0.87051898 0.58236653 0.98340264 0.95213527]
 [0.31250359 0.0809058  0.66424986 0.17408105]
 [0.02295876 0.23725966 0.84960195 0.18986984]
 [0.81803112 0.56861288 0.3370055  0.81050672]
 [0.11505427 0.59868549 0.90365831 0.88020951]
 [0.66355139 0.59334687 0.14431103 0.79653506]
 [0.685346   0.11256065 0.89234829 0.14732389]]
first five rows of the array
[[0.49634341 0.26244877 0.9943427  0.94701315]
 [0.14840418 0.8325256  0.38044768 0.47814738]
 [0.24444211 0.02846687 0.39094955 0.1748491 ]
 [0.87051898 0.58236653 0.98340264 0.95213527]
 [0.31250359 0.0809058  0.66424986 0.17408105]]


In [21]:
#6-shuffle numbers between 0 and 10 (inclusive).
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)

print('same result using permutations')
print(np.random.permutation(x))

[8 5 0 7 3 1 6 4 2 9]
same result using permutations
[1 3 7 4 6 2 8 9 0 5]


In [22]:
#7-normalize a 3x3 random matrix
import numpy as np
x=np.random.random((3,3))
print(x)

xmax,xmin=x.max(),x.min()

x=(x-xmin)/(xmax-xmin)
print('after normalization')
print(x)

[[0.68243133 0.07120723 0.82797897]
 [0.90536431 0.24118246 0.51528215]
 [0.65695427 0.9220631  0.75220278]]
after normalization
[[0.71836386 0.         0.88942413]
 [0.98037413 0.19976971 0.52191556]
 [0.68842099 1.         0.80036535]]


In [23]:
#8-create a random vector of size 10 and sort it
import numpy as np
x=np.random.random((10))
print(x)

print('sorted vector')
x.sort()
print(x)

[0.70487825 0.23735727 0.31368862 0.50859905 0.95478772 0.12657453
 0.93423175 0.26454616 0.16238175 0.44063866]
sorted vector
[0.12657453 0.16238175 0.23735727 0.26454616 0.31368862 0.44063866
 0.50859905 0.70487825 0.93423175 0.95478772]


In [29]:
#9-find the nearest value from a given value in an array
import numpy as np
x=np.random.uniform(1,12,5)
print(x)
v=4
n=x.flat[np.abs(x-v).argmin()]
print(n)

[ 8.44407413 10.04620186  1.38111782  2.08652037  9.17906911]
2.0865203735500018


In [30]:
#10-check two random arrays are equal or not
import numpy as np
x=np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)

print('test array x and y are equal or not')
arr_eq=np.allclose(x,y)
print(arr_eq)

First array:
[1 0 1 1 1 0]
Second array:
[0 0 0 1 0 0]
test array x and y are equal or not
False


In [47]:
#16- get the n largest values of an array
import numpy as np
x=np.arange(10)
print("Original array:")
print(x)

np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [48]:
#17- create a three-dimension array with shape (300,400,5) and set to a variable. 
#Fill the array elements with values using unsigned integer (0 to 255).
import numpy as np
np.random.seed(32)
nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)
print(nums)

[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
  [143  20 219 154  85]
  [219 190 170 227 246]
  [ 39  14 127 230 158]]]


In [37]:
#11- random vector of size 15 and replace the maximum value by -1
import numpy as np
x=np.random.random(15)
print("Original array:")
print(x)

x[x.argmax()]=-1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.26706136 0.12009076 0.53032693 0.38221441 0.51167204 0.66190003
 0.65395906 0.87724717 0.46319325 0.8808017  0.84920542 0.54850445
 0.15208389 0.87850181 0.23965968]
Maximum value replaced by -1:
[ 0.26706136  0.12009076  0.53032693  0.38221441  0.51167204  0.66190003
  0.65395906  0.87724717  0.46319325 -1.          0.84920542  0.54850445
  0.15208389  0.87850181  0.23965968]


In [38]:
#12- find point by point distances of a random vector with shape (10,2) representing coordinates
import numpy as np
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0], a[:,1])
d=np.sqrt((x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.24703049 0.19194185 0.74029841 0.61749873 0.2119046
  1.15018747 0.93930629 0.94375614 0.68951286]
 [0.24703049 0.         0.08843535 0.58495579 0.4245998  0.29009036
  1.13400559 0.95901598 0.87894294 0.79392279]
 [0.19194185 0.08843535 0.         0.67002008 0.51273029 0.30106182
  1.19327479 1.00731297 0.94881772 0.81322349]
 [0.74029841 0.58495579 0.67002008 0.         0.19022107 0.57921757
  0.71394823 0.65499269 0.40601477 0.74679296]
 [0.61749873 0.4245998  0.51273029 0.19022107 0.         0.49836777
  0.88166279 0.78716578 0.57988761 0.79941485]
 [0.2119046  0.29009036 0.30106182 0.57921757 0.49836777 0.
  0.93845324 0.73082898 0.73649272 0.51216214]
 [1.15018747 1.13400559 1.19327479 0.71394823 0.88166279 0.93845324
  0.         0.24624687 0.30895703 0.60976257]
 [0.93930629 0.95901598 1.00731297 0.65499269 0.78716578 0.73082898
  0.24624687 0.         0.32184497 0.36373503]
 [0.94375614 0.87894294 0.94881772 0.40601477 0.57988761 0.73649272
  0.30895703 0.321844

In [43]:
#13-find the most frequent value in an array
import numpy as np
x=np.random.randint(0,10,40)
print('original array')
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x))
print(np.bincount(x).argmax())

original array
[1 3 9 1 5 3 7 7 7 7 0 6 1 2 9 6 0 9 0 0 4 4 9 4 7 2 4 4 4 4 7 1 7 4 0 1 9
 8 9 5]
Most frequent value in the above array:
[5 5 2 2 8 2 2 7 1 6]
4


In [44]:
#14- convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates
import numpy as np
z=np.random.random((10,2))
x,y=z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.88965879 0.43792298 0.71580657 0.95644957 0.77977752 0.22260552
 1.12630233 0.9138927  1.02764004 0.97265488]
[0.78483313 0.3580869  0.45579053 0.67922184 1.28947989 0.46805822
 0.57154718 1.49368373 0.42137252 0.07791931]


In [46]:
#15- find the closest value (to a given scalar) in an array
import numpy as np
x=np.arange(100)
print("Original array:")
print(x)

a=np.random.uniform(0,100)
print("Value to compare:")
print(a)

index=(np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
68.4097010015593
68
