In [6]:
#Date-11/30/22
#1-sort a given array of shape 2 along the first axis, last axis and on flattened array
import numpy as np
a=np.array([[10,40],[30,20]])

print("Original array:")
print(a)

print("Sort the array along the first axis:")
print(np.sort(a,axis=0))

print("Sort the array along the last axis:")
print(np.sort(a))

print("Sort the flattened array:")
print(np.sort(a,axis=None))

Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


In [9]:
#2-create a structured array from given student name, height, class and their data types. Now sort the array on height
import numpy as np
data_type=[('name', 'S15'), ('class', int), ('height', float)]
student_details=[('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

# create a structured array
students=np.array(student_details,dtype=data_type)
print("Original array:")
print(students)

print("Sort by height")
print(np.sort(students,order='height'))

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [11]:
#3-create a structured array from given student name, height, class and their data types. 
#Now sort by class, then height if class are equal

import numpy as np
data_type=[('name', 'S15'), ('class', int), ('height', float)]
stud_details=[('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students=np.array(stud_details, dtype=data_type)
print(students)

print("Sort by class, then height if class are equal:")
print(np.sort(students,order=['class', 'height']))

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [12]:
#4-sort the student id with increasing height of the students from given students id and height.
#Print the integer indices that describes the sort order by multiple columns and the sorted data
import numpy as np
student_id=np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height=np.array([40., 42., 45., 41., 38., 40., 42.0])

#Sort by studen_id then by student_height
indices=np.lexsort((student_id, student_height))
print('sorted indices')
print(indices)

print('sorted data')
for n in indices:
    print(student_id[n], student_height[n])

sorted indices
[4 0 5 3 6 1 2]
sorted data
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [13]:
#5-get the indices of the sorted elements of a given array
import numpy as np
stud_id=np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(stud_id)

i=np.argsort(stud_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


In [19]:
#6-sort a given complex array using the real part first, then the imaginary part.
import numpy as np

complex_num=[1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]
print("Original array:")
print(complex_num)

print("\nSorted a given complex array using the real part first, then the imaginary part.")
print(np.sort_complex(complex_num))

Original array:
[(1+2j), (3-1j), (3-2j), (4-3j), (3+5j)]

Sorted a given complex array using the real part first, then the imaginary part.
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


In [21]:
#7-partition a given array in a specified position and move all the smaller elements values 
#to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice). 

import numpy as np
nums=np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums,4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


In [22]:
#8-sort the specified number of elements from beginning of a given array.
import numpy as np
nums=np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])

Original array:
[0.14533079 0.43377168 0.17304545 0.84184612 0.6085817  0.61769342
 0.73567644 0.81778281 0.04320673 0.27605693]

Sorted first 5 elements:
[0.04320673 0.14533079 0.17304545 0.27605693 0.43377168 0.61769342
 0.73567644 0.81778281 0.6085817  0.84184612]


In [23]:
#9-sort an given array by the nth column.
import numpy as np
print('original array')
nums=np.random.randint(0,10,(3,3))
print(nums)

print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

original array
[[4 8 3]
 [4 8 5]
 [5 6 3]]

Sort the said array by the nth column: 
[[5 6 3]
 [4 8 3]
 [4 8 5]]
